server {
    listen 80;
    server_name _;

    root /srv/monorepo/current/root;

    location /modules/ {
        alias /srv/monorepo/current/modules/;
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
